# Generated by Django 2.2.4 on 2019-10-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20191020_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_bucket',
            name='checked_out',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='checked_out'),
        ),
        migrations.AlterField(
            model_name='cart_bucket',
            name='create_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='create_date'),
        ),
    ]
