# Generated by Django 2.2.4 on 2019-10-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20191020_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_total',
            field=models.IntegerField(default=1),
        ),
    ]
