# Generated by Django 2.2.4 on 2019-10-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_auto_20191024_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
